### ISSUE TITLE
tutorial: difference between this library and ppl

### ISSUE THREAD

**Issue by mediabuff** [lewissbaker/cppcoro#56]
1) for a novice, what is the conceptual difference
2) is the task here similar to the task in ppl
3) does this library rely on a thread pool

**Comment by lewissbaker** [comment]
Sorry for the delay in replying.

I'll try and answer your questions as best I can, but I'm not an expert in PPL so please forgive me any inaccuracies.

This library is built on top of the Coroutines TS and uses coroutines as the fundamental building-block for implementing continuations, rather than callbacks. This allows you to write asynchronous code more simply without need to break up your functions into callbacks for each synchronously executing part.

PPL tasks represent computations that are executed in parallel on a thread-pool. You typically construct a PPL task with a callback/lambda that you want executed on the thread-pool and it will get scheduled. You can then attach a continuation for that task using `.then()`.

The cppcoro task has some conceptual similarities at a high level but has a few differences.
Namely, you create a cppcoro task by calling a coroutine function, the body of which defines the state-machine for executing the operations within a task. A cppcoro::task is not automatically executed on the thread-pool, it will start executing on whatever thread `co_await`s the `task`.

cppcoro can in theory be used without a thread-pool, although many of the low-level async operations require a scheduler of some sort to schedule resumption of coroutines when operations complete. The `io_service` class can be used to implement a thread-pool, however I also plan to add a thread-pool to cppcoro as well.

**Comment by mediabuff** [comment]
Thank you. Great library!
